# Generated by Django 5.2.18 on 2026-10-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_pakistan_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('window_start', models.DateTimeField()),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
