# Generated by Django 5.2.18 on 2026-10-07 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_schedule_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='note',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='source',
            field=models.CharField(choices=[('punch', 'Punch'), ('manual', 'Manual'), ('adjusted', 'Adjusted'), ('admin', 'Admin correction')], default='punch', max_length=10),
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Added'), ('changed', 'Changed'), ('removed', 'Removed')], max_length=10)),
                ('old_clock_in', models.DateTimeField(blank=True, null=True)),
                ('old_clock_out', models.DateTimeField(blank=True, null=True)),
                ('new_clock_in', models.DateTimeField(blank=True, null=True)),
                ('new_clock_out', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='attendance.timeentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
